### ISSUE TITLE
Errors from vscode console

### ISSUE THREAD

**Issue by enthus1ast** [saem/vscode-nim#11]
I've just installed the extensions via the VSCode plugin manager.
It syntax highlights, but not much else is working, i also get this error message in the developer console:

```
  ERR The "path" argument must be of type string. Received type undefined: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
	at validateString (internal/validators.js:112:11)
	at Object.join (path.js:375:7)
	at getDirtyFile_11885258 (c:\Users\david\.vscode\extensions\nimsaem.nimvscode-0.1.8\out\nimvscode.js:7208:76)
	at HEX3Aanonymous_12396058 (c:\Users\david\.vscode\extensions\nimsaem.nimvscode-0.1.8\out\nimvscode.js:7835:102)
	at new Promise (<anonymous>)
	at Object.provideDefinition_12396041 [as provideDefinition] (c:\Users\david\.vscode\extensions\nimsaem.nimvscode-0.1.8\out\nimvscode.js:7844:23)
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:732:906
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:51:976
	at new Promise (<anonymous>)
	at Object.t.asPromise (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:51:948)
	at w.provideDefinition (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:732:877)
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:753:861
	at K._withAdapter (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:752:10)
	at K.$provideDefinition (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:753:839)
	at m._doInvokeHandler (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:870:464)
	at m._invokeHandler (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:870:156)
	at m._receiveRequest (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:868:766)
	at m._receiveOneMessage (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:867:623)
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:865:691
	at l.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1059:179
	at l.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at p.acceptChunk (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\david\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by saem** [comment]
@enthus1ast bummer, the original extension had similar issues of memory serves. Let me see if I can help you debug a bit. It was also often Windows based, which I don't have.

The nimvscode.js file is the entire extension, so you don't have to bounce around files too much, yay! The functions like HEX3Anonymous and otherwise normal names with a number at the end are nice and searchable.

I believe the Nim source file name and line numbers are in the js file either as comments or as variables. First step please see what path it's having trouble finding, I have an idea but would appreciate the confirmation.

**Comment by saem** [comment]
@enthus1ast looks like you're using windows there were a few changes, though tangential that might change the behaviour of the extension for you. If it's still a problem let me know.

**Comment by saem** [comment]
Going to assume this is fixed.

**Comment by RSDuck** [comment]
yeah this looks exactly like the nim check parsing stuff I fixed/am fixing
